#include "PluginEditor.h"
#include <BinaryData.h>

DelayLamaEditor::DelayLamaEditor(DelayLamaProcessor& p): AudioProcessorEditor(&p),processor(p) {
    faceSheet=juce::ImageCache::getFromMemory(BinaryData::facematrix_8bit_png,BinaryData::facematrix_8bit_pngSize);
    background=juce::ImageCache::getFromMemory(BinaryData::background_8bit_png,BinaryData::background_8bit_pngSize);
    setSize(760,600); setResizable(true,true); setResizeLimits(640,520,1100,820);
    title.setText("DELAY LAMA",juce::dontSendNotification); title.setFont(juce::Font(juce::FontOptions(24.0f,juce::Font::bold))); title.setColour(juce::Label::textColourId,juce::Colour(0xfff1d58a)); addAndMakeVisible(title);
    hint.setText("MONOPHONIC FORMANT GRAIN SYNTH",juce::dontSendNotification); hint.setFont(juce::Font(juce::FontOptions(11.0f))); hint.setColour(juce::Label::textColourId,juce::Colour(0xffddc9a5)); addAndMakeVisible(hint);
    auto setup=[&](juce::Slider& s,const char* name){s.setSliderStyle(juce::Slider::RotaryHorizontalVerticalDrag);s.setTextBoxStyle(juce::Slider::TextBoxBelow,false,70,18);s.setNumDecimalPlacesToDisplay(2);s.setName(name);s.setColour(juce::Slider::rotarySliderFillColourId,juce::Colour(0xffd5a548));s.setColour(juce::Slider::thumbColourId,juce::Colour(0xffffe5a2));addAndMakeVisible(s);};
    setup(glide,"GLIDE");setup(delay,"DELAY");setup(head,"HEAD");setup(pitch,"PITCH");
    input.setName("MIC / AUDIO INPUT"); input.setSliderStyle(juce::Slider::LinearHorizontal); input.setTextBoxStyle(juce::Slider::TextBoxRight,false,52,20); input.setRange(0,1); input.setNumDecimalPlacesToDisplay(2); input.setColour(juce::Slider::trackColourId,juce::Colour(0xffd5a548)); input.setColour(juce::Slider::thumbColourId,juce::Colour(0xffffe5a2)); addAndMakeVisible(input);
    glide.setRange(0,1);delay.setRange(0,1);head.setRange(0,1);pitch.setRange(36,84,1);
    glideAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(processor.state,"glide",glide);
    delayAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(processor.state,"delay",delay);
    headAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(processor.state,"head",head);
    pitchAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(processor.state,"pitch",pitch);
    inputAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(processor.state,"input",input);
    setWantsKeyboardFocus(true); addKeyListener(this); const std::array<juce::Component*,5> keyTargets{&glide,&delay,&head,&pitch,&input}; for(auto* c:keyTargets)c->addKeyListener(this);
    startTimerHz(12);
}
void DelayLamaEditor::resized(){auto b=getLocalBounds().reduced(24); title.setBounds(b.removeFromTop(34));hint.setBounds(b.removeFromTop(22));keyboard=b.removeFromBottom(82);pad={b.getX()+15,b.getY()+14,(int)(getWidth()*.49),b.getHeight()-44};int x=pad.getRight()+28,y=b.getY()+5,w=getWidth()-x-34;glide.setBounds(x,y,w/2,112);delay.setBounds(x+w/2,y,w/2,112);head.setBounds(x,y+126,w/2,112);pitch.setBounds(x+w/2,y+126,w/2,112);input.setBounds(x,y+264,w,42);}
void DelayLamaEditor::paint(juce::Graphics& g){g.fillAll(juce::Colour(0xff201712));auto area=getLocalBounds().toFloat();g.setColour(juce::Colour(0xff3a291b));g.fillRoundedRectangle(area.reduced(7),18);g.setColour(juce::Colour(0xffd1a34d));g.drawRoundedRectangle(area.reduced(8),18,2);g.setColour(juce::Colour(0xff17120f));g.fillRoundedRectangle(pad.toFloat(),14);
    if(faceSheet.isValid()){const int col=juce::jlimit(0,4,(int)(processor.state.getRawParameterValue("vowel")->load()*5));const int row=(juce::uint32(juce::Time::getMillisecondCounter()/240)%6);g.drawImage(faceSheet,pad.getX()+6,pad.getY()+6,pad.getWidth()-12,pad.getHeight()-12,col*314,row*311,314,280);}
    g.setColour(juce::Colour(0x99ffe39d));g.drawRoundedRectangle(pad.toFloat(),14,2);auto marker=juce::Point<float>(pad.getX()+(processor.state.getRawParameterValue("pitch")->load()-36.0f)/48.0f*pad.getWidth(),pad.getY()+processor.state.getRawParameterValue("vowel")->load()*pad.getHeight());g.setColour(juce::Colours::white.withAlpha(.85f));g.fillEllipse(marker.x-6,marker.y-6,12,12);
    g.setColour(juce::Colour(0xffd7bd91));for(auto* s:{&glide,&delay,&head,&pitch})g.drawFittedText(s->getName(),s->getBounds().withY(s->getBounds().getY()-8).withHeight(18),juce::Justification::centred,1);g.drawFittedText("MIC / AUDIO INPUT LEVEL",input.getBounds().withY(input.getBounds().getY()-16).withHeight(15),juce::Justification::left,1);
    g.setColour(juce::Colour(0xfff1d58a));g.drawText("PLAY   |   COMPUTER KEYS: A W S E D F T G Y H U J K",keyboard.getX(),keyboard.getY()-19,keyboard.getWidth(),16,juce::Justification::left);
    const int activeKey=computerNote>=60?computerNote-60:pressedKey;const float keyW=keyboard.getWidth()/7.0f, keyH=(float)keyboard.getHeight(); const int whiteNotes[7]={0,2,4,5,7,9,11};
    const char* noteNames[7]={"C4","D4","E4","F4","G4","A4","B4"};for(int k=0;k<7;++k){juce::Rectangle<float> key(keyboard.getX()+k*keyW,keyboard.getY(),keyW,keyH);g.setColour(activeKey==whiteNotes[k]?juce::Colour(0xffffdf8a):juce::Colour(0xfff3ead8));g.fillRect(key);g.setColour(juce::Colour(0xff583d27));g.drawRect(key,1.0f);g.setColour(juce::Colour(0xff6a553d));g.drawText(noteNames[k],key.toNearestInt().withTrimmedTop(keyboard.getHeight()-20),juce::Justification::centredBottom);}
    const int blackNotes[5]={1,3,6,8,10}, whiteBefore[5]={0,1,3,4,5}; const float blackW=keyW*.58f;
    for(int k=0;k<5;++k){juce::Rectangle<float> key(keyboard.getX()+(whiteBefore[k]+1)*keyW-blackW*.5f,keyboard.getY(),blackW,keyH*.61f);g.setColour(activeKey==blackNotes[k]?juce::Colour(0xffbd8a35):juce::Colour(0xff27211d));g.fillRoundedRectangle(key,3.0f);g.setColour(juce::Colour(0xff9b7c4c));g.drawRoundedRectangle(key,3.0f,1.0f);}
}
int DelayLamaEditor::keyAt(juce::Point<int> point) const {if(!keyboard.contains(point))return -1;const float keyW=keyboard.getWidth()/7.0f, x=(float)(point.x-keyboard.getX());const int blackNotes[5]={1,3,6,8,10}, whiteBefore[5]={0,1,3,4,5};const float blackW=keyW*.58f;for(int k=0;k<5;++k){const float left=(whiteBefore[k]+1)*keyW-blackW*.5f;if(x>=left&&x<left+blackW&&point.y<keyboard.getY()+keyboard.getHeight()*.61f)return blackNotes[k];}const int whiteNotes[7]={0,2,4,5,7,9,11};return whiteNotes[juce::jlimit(0,6,(int)(x/keyW))];}
void DelayLamaEditor::updateUiNote(){const int note=computerNote>=0?computerNote:(pressedKey>=0?60+pressedKey:-1);if(note!=sentUiNote){processor.setUiNote(note,note>=0);sentUiNote=note;}}
void DelayLamaEditor::updatePressedKey(juce::Point<int> p){const int key=keyAt(p);if(key==pressedKey)return;pressedKey=key;updateUiNote();repaint();}
void DelayLamaEditor::mouseDown(const juce::MouseEvent& e){grabKeyboardFocus();if(keyboard.contains(e.getPosition())){updatePressedKey(e.getPosition());return;}mouseDrag(e);} void DelayLamaEditor::mouseDrag(const juce::MouseEvent& e){if(pressedKey>=0||keyboard.contains(e.getPosition())){updatePressedKey(e.getPosition());return;}if(!pad.contains(e.getPosition()))return;auto x=(float)(e.x-pad.getX())/pad.getWidth(),y=(float)(e.y-pad.getY())/pad.getHeight();processor.state.getParameter("pitch")->setValueNotifyingHost(juce::jlimit(0.0f,1.0f,x));processor.state.getParameter("vowel")->setValueNotifyingHost(juce::jlimit(0.0f,1.0f,y));repaint();}
void DelayLamaEditor::mouseUp(const juce::MouseEvent&){if(pressedKey>=0){pressedKey=-1;updateUiNote();repaint();}}
void DelayLamaEditor::focusLost(FocusChangeType){if(computerNote>=0){computerNote=-1;std::fill(std::begin(computerKeysDown),std::end(computerKeysDown),false);updateUiNote();repaint();}}
void DelayLamaEditor::visibilityChanged(){if(isShowing())grabKeyboardFocus();}
bool DelayLamaEditor::handleComputerKeyPress(const juce::KeyPress& key){const int codes[13]={'a','w','s','e','d','f','t','g','y','h','u','j','k'};const int code=juce::CharacterFunctions::toLowerCase((juce::juce_wchar)key.getKeyCode());for(int i=0;i<13;++i)if(code==codes[i]){computerKeysDown[i]=true;computerNote=60+i;updateUiNote();repaint();return true;}return false;}
bool DelayLamaEditor::handleComputerKeyState(bool isDown){if(isDown)return false;const int codes[13]={'a','w','s','e','d','f','t','g','y','h','u','j','k'};bool hadNote=computerNote>=0;computerNote=-1;for(int i=0;i<13;++i){computerKeysDown[i]=juce::KeyPress::isKeyCurrentlyDown(codes[i]);if(computerKeysDown[i])computerNote=60+i;}if(hadNote||computerNote>=0){updateUiNote();repaint();return true;}return false;}
bool DelayLamaEditor::keyPressed(const juce::KeyPress& k,juce::Component*){return handleComputerKeyPress(k);} bool DelayLamaEditor::keyStateChanged(bool d,juce::Component*){return handleComputerKeyState(d);}
bool DelayLamaEditor::keyPressed(const juce::KeyPress& k){return handleComputerKeyPress(k);} bool DelayLamaEditor::keyStateChanged(bool d){return handleComputerKeyState(d);}
void DelayLamaEditor::timerCallback(){repaint();}
